### ISSUE TITLE
This package is unmaintained and does not works with up to date SymPy versions

### ISSUE THREAD

**Issue by tansey** [cdsousa/PyLMI-SDP#4]
Running the first example from the readme is failing:

```
lmi = LMI_PD(Matrix([[x+1, y+2], [y+2, z+x]]))
```

Yields the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lmi_sdp/lmi.py", line 129, in __new__
    assert_symmetry)
  File "/usr/local/lib/python2.7/site-packages/lmi_sdp/lmi.py", line 38, in __new__
    return rel_cls.__new__(cls, lhs, rhs)
  File "/usr/local/lib/python2.7/site-packages/sympy/core/relational.py", line 295, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "/usr/local/lib/python2.7/site-packages/sympy/core/relational.py", line 616, in _eval_relation
    return _sympify(lhs.__gt__(rhs))
  File "/usr/local/lib/python2.7/site-packages/sympy/matrices/matrices.py", line 3084, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: ImmutableMatrix has no attribute __gt__.
```

**Comment by spacedmi** [comment]
Hello. Did you solve this issue?

**Comment by cdsousa** [comment]
Hi, it seems this issue have escaped my attention.

I have not used this package for some time and I won't use it in foreseeable future.

That seems to be a bug introduced by some breaking changes in the SymPy dependency...
I, myself, am getting another error probably by the same reason.

I do not have much free time, but I'll try to take a look.
Don't way for me though, this is a very small package and it may be quicker to you to look at the source code and fix it.

**Comment by spacedmi** [comment]
Thanks for the answer. If I have free time I'm going to fix it by myself.

2015-12-13 1:33 GMT+03:00 Cristóvão Duarte Sousa <notifications@github.com>:

> Hi, it seems this issue have escaped my attention.
>
> I have not used this package for some time and I won't use it in
> foreseeable future.
>
> That seems to be a bug introduced by some breaking changes in the SymPy
> dependency...
> I, myself, am getting another error probably by the same reason.
>
> I do not have much free time, but I'll try to take a look.
> Don't way for me though, this is a very small package and it may be
> quicker to you to look at the source code and fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdsousa/PyLMI-SDP/issues/4#issuecomment-164199312>.
>



-- 
С уважением,
Тарасов Дмитрий

**Comment by spacedmi** [comment]
I have installed SymPy 0.7.3, and use your code without issues. Thank you

2015-12-13 11:30 GMT+03:00 Дмитрий Тарасов <spacedmi@gmail.com>:

> Thanks for the answer. If I have free time I'm going to fix it by myself.
>
> 2015-12-13 1:33 GMT+03:00 Cristóvão Duarte Sousa <notifications@github.com
> >:
>
>> Hi, it seems this issue have escaped my attention.
>>
>> I have not used this package for some time and I won't use it in
>> foreseeable future.
>>
>> That seems to be a bug introduced by some breaking changes in the SymPy
>> dependency...
>> I, myself, am getting another error probably by the same reason.
>>
>> I do not have much free time, but I'll try to take a look.
>> Don't way for me though, this is a very small package and it may be
>> quicker to you to look at the source code and fix it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cdsousa/PyLMI-SDP/issues/4#issuecomment-164199312>.
>>
>
>
>
> --
> С уважением,
> Тарасов Дмитрий
>



-- 
С уважением,
Тарасов Дмитрий

**Comment by cdsousa** [comment]
What version was it before?

**Comment by spacedmi** [comment]
SymPy 0.7.6.1

2015-12-13 13:13 GMT+03:00 Cristóvão Duarte Sousa <notifications@github.com>
:

> What version was it before?
>
> On Sun, Dec 13, 2015 at 8:42 AM Dmitry Tarasov <notifications@github.com>
> wrote:
>
> > I have installed SymPy 0.7.3, and use your code without issues. Thank you
> >
> > 2015-12-13 11:30 GMT+03:00 Дмитрий Тарасов <spacedmi@gmail.com>:
> >
> > > Thanks for the answer. If I have free time I'm going to fix it by
> myself.
> > >
> > > 2015-12-13 1:33 GMT+03:00 Cristóvão Duarte Sousa <
> > notifications@github.com
> > > >:
> > >
> > >> Hi, it seems this issue have escaped my attention.
> > >>
> > >> I have not used this package for some time and I won't use it in
> > >> foreseeable future.
> > >>
> > >> That seems to be a bug introduced by some breaking changes in the
> SymPy
> > >> dependency...
> > >> I, myself, am getting another error probably by the same reason.
> > >>
> > >> I do not have much free time, but I'll try to take a look.
> > >> Don't way for me though, this is a very small package and it may be
> > >> quicker to you to look at the source code and fix it.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/cdsousa/PyLMI-SDP/issues/4#issuecomment-164199312
> >.
> > >>
> > >
> > >
> > >
> > > --
> > > С уважением,
> > > Тарасов Дмитрий
> > >
> >
> >
> >
> > --
> > С уважением,
> > Тарасов Дмитрий
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cdsousa/PyLMI-SDP/issues/4#issuecomment-164239364>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdsousa/PyLMI-SDP/issues/4#issuecomment-164244304>.
>



-- 
С уважением,
Тарасов Дмитрий

**Comment by kjyv** [comment]
Downgrading SymPy is not really a solution. The issue seems that in various relations like GreaterThan in sympy's relational.py, the expression `lhs > rhs` has been changed to `_sympify(lhs.__gt__(rhs))` which is not defined for matrices. 
Not sure if this is a bug in sympy. Should _gt_ etc be defined for matrices as well? I actually wonder why > works when __gt__ is not implemented...

**Comment by asmeurer** [comment]
`>` (`Gt`) in SymPy doesn't work with matrices.

**Comment by kjyv** [comment]
Thats not true, lhs > rhs returns True or False. I couldn't find any place though saying what that is supposed to mean. Something did work with 0.7.3 that now behaves differently.

**Comment by asmeurer** [comment]
Maybe that works in Python 2, but that's just because Python 2 has a default implementation for `__gt__`. In Python 3, I get

```
In [6]: Matrix([[1, 2], [3, 4]]) > Matrix([[1, 2], [4, 3]])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-9fe5fdf91ec0> in <module>()
----> 1 Matrix([[1, 2], [3, 4]]) > Matrix([[1, 2], [4, 3]])

TypeError: unorderable types: MutableDenseMatrix() > MutableDenseMatrix()
```

**Comment by kjyv** [comment]
Yeah, thats possible. I think there are also other incompatibilities with python 3

**Comment by kjyv** [comment]
Point is, pylmi-sdp does not work anymore with sympy > 0.7.3 and python 2.7. If and how this part worked in python 3 (supposedly yes at some point) I don't know but with newer sympy the same problem should occur. A proper solution needs to express the positive definite relation somehow differently.

**Comment by cdsousa** [comment]
Well, I took a quick look at this and it seema the whole package has been built around the use of `sympy.core.relational.GreaterThan` and others with `sympy.matrices.dense.MutableDenseMatrix.

**Comment by kjyv** [comment]
Yes, GreaterThan, StrictGreaterThan etc. are used to represent the inequalities, which worked with older sympy versions. Now even creating an instance of e.g. GreaterThan will call __ge__ on the lhs side, which is not defined for matrices. It is however possible to use >, >= etc instead in newer versions. I've tried it also in python 3.5. A simple workaround would be to check for the sympy version and use one or the other. Maybe a better way is to keep lhs and rhs separate in the classes, but probably then pretty printing and all that would not work that easily anymore.

**Comment by cdsousa** [comment]
That seems a good solution indeed. We would need to store `lhs`, `rhs` and `rel_op`. Printing wouldn't be that problematic I guess, https://github.com/cdsousa/PyLMI-SDP/blob/cac22772feeff1f7d3366d89c9d3d1a977e14eb1/lmi_sdp/lmi.py#L162  . I don't remember what other benefits were obtained with the current approach though.

**Comment by hustfzt2** [comment]
"TypeError: 'LessThan' object is not callable" occured when i run the example in x.canonical()

**Comment by cdsousa** [comment]
This package is unmaintained (by me) and does not works with up to date SymPy versions.
Unfortunately, I have absolutely no time to fix it.
