### ISSUE TITLE
some errors occur when i run the test code 

### ISSUE THREAD

**Issue by qweesiic** [cdsousa/PyLMI-SDP#5]
![Screenshot from 2019-08-01 09-59-46](https://user-images.githubusercontent.com/53546804/62260042-20f13d00-b443-11e9-97ca-2d6ab2e46ea6.png)
the upper image happened when i use the fuction "test_LMI_PSD()" in the file'test_lmi.py '

the lower image happened when i use the fuction "test_LMI_canonical()" in the file'test_lmi.py '
![Screenshot from 2019-08-01 10-01-17](https://user-images.githubusercontent.com/53546804/62260080-526a0880-b443-11e9-88c3-37f54b979549.png)

And python version in my laptop is Python 3.5.2

**Comment by hustfzt2** [comment]
Hi，have you fixed your issues?

**Comment by cdsousa** [comment]
This is probably the same problem as https://github.com/cdsousa/PyLMI-SDP/issues/4
